// client/src/App.tsx
import React, { useEffect } from "react";
import {
	BrowserRouter as Router,
	Route,
	Routes,
} from "react-router-dom";
import { io, Socket } from "socket.io-client";

import { Header } from "./components/Header/Header";
import OauthHandler from "./components/OAuthHandler";
import RoomList from "./components/RoomList/RoomList";
import VM from "./components/VM";
import { UserData } from "./scripts/auth";

function socketHandler() {
	const socket = io(import.meta.env.VITE_API_SERVER_BASE_URL, {

	});
	socket.on("connect", () => {
		console.log("Connected to server");
	});
	return socket;
}

interface AppState {
	user?: UserData;
	socket?: Socket;
	loaded: boolean;
}


function App() {
	const [state, setState] = React.useState<AppState>({ loaded: false });
	const setUser = (user?: UserData) => { setState({ ...state, user }); };
	useEffect(() => {
		if (!state.loaded) {
			const socket = socketHandler();
			socket.on("connect", () => {
				setState({ ...state, loaded: true, socket });
				console.log("Connected to server");
			});
		}
	});
	return (
		<Router>
			<div className="App">
				<Header user={state.user} setUser={setUser} />
				<Routes>
					<Route path="/" element={<RoomList />} />
					<Route path="/authorize" element={<OauthHandler user={state.user} setUser={setUser} />} />
					<Route path="/rooms/:id" element={<VM />} />
				</Routes>
			</div>
		</Router>
	);
}

export default App;

// client/src/App.svelte
<script lang="ts">
	import { Manager } from "socket.io-client";
	import { onMount } from "svelte";
	import { Route, Router } from "svelte-navigator";

	import Authorize from "./pages/Authorize.svelte";
	import Lander from "./pages/Lander.svelte";
	import Room from "./pages/Room.svelte";
	import Roomlist from "./pages/Roomlist.svelte";
	import { login } from "./scripts/api";
	import { manager } from "./scripts/state";

	const socketManager = new Manager(import.meta.env.VITE_API_SERVER_BASE_URL, {
		withCredentials: true,
		autoConnect: true,
		path: import.meta.env.VITE_CLIENT_SOCKET_URL,
	});

	onMount(async () => {
		console.log("Mounted app component");
		if (localStorage.getItem("token")) {
			try {
				await login().then(() => {
					console.log("Logged in");
					$manager = socketManager;
				});
			} catch (e) {
				console.error(e);
				localStorage.removeItem("token");
			}
		}
	});
</script>

<div>
	<Router primary={false}>
		<!-- <Header /> -->
		<Route path="/" component={Lander} />
		<Route path="/rooms" component={Roomlist} />
		<Route path="/authorize" component={Authorize} />
		<Route path="/:roomUrl" component={Room} />
	</Router>
</div>
