// client/src/components/Avatar/Avatar.tsx
import "./Avatar.css";

import React from "react";

interface IProps {
  img: string;
  alt: string;
  boderStyle?: "dashed" | "solid";
}

export default function Avatar({ img, alt, boderStyle }: IProps) {
	return (
		<div
			className={`avatar ${
				boderStyle === "dashed"
					? "avatar-dashed"
					: boderStyle === "solid"
						? "avatar-solid"
						: ""
			}`}
		>
			<img src={img} alt={alt} />
		</div>
	);
}

// client/src/components/Avatar.svelte
<script lang="ts">
  export let src: string;
  export let alt: string;
  export let borderStyle: "dashed" | "solid";
</script>

<div
  class={`avatar ${
    borderStyle === "dashed"
      ? "avatar-dashed"
      : borderStyle === "solid"
      ? "avatar-solid"
      : ""
  }`}
>
  <img {src} {alt} />
</div>

<style>
  .avatar {
    aspect-ratio: 1 / 1;
    width: 40px;
    padding: 2px;
    border-radius: 50%;
  }

  .avatar-dashed {
    border: 2px dashed blueviolet;
  }

  .avatar-solid {
    border: 2px solid blueviolet;
  }

  .avatar img {
    width: 100%;
    height: 100%;
    border-radius: 50%;
  }
</style>
