// client/src/components/VM.svelte
<script lang="ts">
  import Hyperbeam from "@hyperbeam/web";
  import { onMount } from "svelte";
  export let embedUrl: string;

  async function startHyperbeamSession(url) {
  	const hbiframe = document.getElementById(
  		"hyperbeam",
  	) as HTMLIFrameElement | null;
  	if (hbiframe) return Hyperbeam(hbiframe, url);
  }
  // TODO: consolidate api interactions in one place?
  $: startHyperbeamSession(embedUrl);

  onMount(async () => {
  	if (embedUrl) startHyperbeamSession(embedUrl);
  });
</script>

<div id="VM">
  <iframe id="hyperbeam" title="Hyperbeam" />
</div>

<style>
  #VM {
    height: 100vh;
    width: 100vw;
  }

  #hyperbeam {
    width: 100%;
    height: 100%;
    aspect-ratio: 16 / 9; /* TODO: check support */
  }
</style>

// client/src/components/VM.tsx
import Hyperbeam from "@hyperbeam/iframe";
import React, { useEffect } from "react";
import { useParams } from "react-router-dom";

// TODO: consolidate api interactions in one place?
async function startHyperbeamSession(id: string) {
	const response = await fetch(`${import.meta.env.VITE_API_SERVER_BASE_URL}/${id}`);
	if (response.ok) {
		const data = await response.json();
		const hbiframe = document.getElementById("hyperbeam") as HTMLIFrameElement | null;
		if (hbiframe) return Hyperbeam(hbiframe, data.embedUrl);
	}
}

// TODO: vm do be tiny tho
export default function VM() {
	const { id } = useParams();
	useEffect(() => {
		if (id)
			startHyperbeamSession(id);
	}, [id]);
	return <div>
		<h2>VM</h2>
		<iframe id="hyperbeam" title="Hyperbeam" />
	</div>;
}
